//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programmer.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Programmer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на binary_buffer.
        /// </summary>
        internal static string BINARY_BUFFER_NAME {
            get {
                return ResourceManager.GetString("BINARY_BUFFER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .bin.
        /// </summary>
        internal static string BINARY_FILE_EXTENSION {
            get {
                return ResourceManager.GetString("BINARY_FILE_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на bootloader.
        /// </summary>
        internal static string BOOTLOADER_NAME {
            get {
                return ResourceManager.GetString("BOOTLOADER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .csv.
        /// </summary>
        internal static string CSV_FILE_EXTANSION {
            get {
                return ResourceManager.GetString("CSV_FILE_EXTANSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ;.
        /// </summary>
        internal static string CSV_SEPARATOR {
            get {
                return ResourceManager.GetString("CSV_SEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на default_layout.
        /// </summary>
        internal static string DEFAULT_LAYOUT_FILE_NAME {
            get {
                return ResourceManager.GetString("DEFAULT_LAYOUT_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на eeprom.
        /// </summary>
        internal static string EEPROM_NAME {
            get {
                return ResourceManager.GetString("EEPROM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на firmware.
        /// </summary>
        internal static string FIRMWARE_NAME {
            get {
                return ResourceManager.GetString("FIRMWARE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на flash.
        /// </summary>
        internal static string FLASH_NAME {
            get {
                return ResourceManager.GetString("FLASH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_MEK_Configurator {
            get {
                object obj = ResourceManager.GetObject("Icon_MEK_Configurator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon Icon_MEK_Configurator1 {
            get {
                object obj = ResourceManager.GetObject("Icon_MEK_Configurator1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .mek.
        /// </summary>
        internal static string LAYOUT_FILE_EXTENSION {
            get {
                return ResourceManager.GetString("LAYOUT_FILE_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на :.
        /// </summary>
        internal static string LAYOUT_SEPARATOR {
            get {
                return ResourceManager.GetString("LAYOUT_SEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Mini Editor Keyboard DFU&quot;.
        /// </summary>
        internal static string NAME_DFU_MODE {
            get {
                return ResourceManager.GetString("NAME_DFU_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на bin/.
        /// </summary>
        internal static string PATH_BINARY {
            get {
                return ResourceManager.GetString("PATH_BINARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на cfg/.
        /// </summary>
        internal static string PATH_CONFIG {
            get {
                return ResourceManager.GetString("PATH_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на cfg/colors/.
        /// </summary>
        internal static string PATH_CONFIG_COLORS {
            get {
                return ResourceManager.GetString("PATH_CONFIG_COLORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на cfg/tools/.
        /// </summary>
        internal static string PATH_CONFIG_TOOLS {
            get {
                return ResourceManager.GetString("PATH_CONFIG_TOOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на win\utils\dfu-util-0.9-win64\dfu-util.exe.
        /// </summary>
        internal static string PATH_DFU_UTIL {
            get {
                return ResourceManager.GetString("PATH_DFU_UTIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на win/drivers/dfu.
        /// </summary>
        internal static string PATH_DRIVER_DFU {
            get {
                return ResourceManager.GetString("PATH_DRIVER_DFU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на win\drivers\st-link\dpinst_amd64.exe.
        /// </summary>
        internal static string PATH_DRIVER_ST_LINK_64 {
            get {
                return ResourceManager.GetString("PATH_DRIVER_ST_LINK_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на win\drivers\st-link\dpinst_x86.exe.
        /// </summary>
        internal static string PATH_DRIVER_ST_LINK_86 {
            get {
                return ResourceManager.GetString("PATH_DRIVER_ST_LINK_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на win\utils\stlink\ST-LINK_CLI.exe.
        /// </summary>
        internal static string PATH_ST_LINK {
            get {
                return ResourceManager.GetString("PATH_ST_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на win\utils\wdi\wdi-simple.exe.
        /// </summary>
        internal static string PATH_WDI {
            get {
                return ResourceManager.GetString("PATH_WDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://github.com/S-LABc/DVR-Mini-Editor-Keyboard.
        /// </summary>
        internal static string PROJECT_WEB_LINK {
            get {
                return ResourceManager.GetString("PROJECT_WEB_LINK", resourceCulture);
            }
        }
    }
}
