//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programmer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Undo")]
        public string cmbKey1 {
            get {
                return ((string)(this["cmbKey1"]));
            }
            set {
                this["cmbKey1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Snapping")]
        public string cmbKey2 {
            get {
                return ((string)(this["cmbKey2"]));
            }
            set {
                this["cmbKey2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cinema Viewer")]
        public string cmbKey3 {
            get {
                return ((string)(this["cmbKey3"]));
            }
            set {
                this["cmbKey3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Insert")]
        public string cmbKey4 {
            get {
                return ((string)(this["cmbKey4"]));
            }
            set {
                this["cmbKey4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Append to End of Timeline")]
        public string cmbKey5 {
            get {
                return ((string)(this["cmbKey5"]));
            }
            set {
                this["cmbKey5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ripple Overwrite")]
        public string cmbKey6 {
            get {
                return ((string)(this["cmbKey6"]));
            }
            set {
                this["cmbKey6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fit to Fill")]
        public string cmbKey7 {
            get {
                return ((string)(this["cmbKey7"]));
            }
            set {
                this["cmbKey7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Place on Top")]
        public string cmbKey8 {
            get {
                return ((string)(this["cmbKey8"]));
            }
            set {
                this["cmbKey8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Replace")]
        public string cmbKey9 {
            get {
                return ((string)(this["cmbKey9"]));
            }
            set {
                this["cmbKey9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mark In")]
        public string cmbKey10 {
            get {
                return ((string)(this["cmbKey10"]));
            }
            set {
                this["cmbKey10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Add Marker")]
        public string cmbKey11 {
            get {
                return ((string)(this["cmbKey11"]));
            }
            set {
                this["cmbKey11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mark Out")]
        public string cmbKey12 {
            get {
                return ((string)(this["cmbKey12"]));
            }
            set {
                this["cmbKey12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resize In")]
        public string cmbKey13 {
            get {
                return ((string)(this["cmbKey13"]));
            }
            set {
                this["cmbKey13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resize Out")]
        public string cmbKey14 {
            get {
                return ((string)(this["cmbKey14"]));
            }
            set {
                this["cmbKey14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Roll")]
        public string cmbKey15 {
            get {
                return ((string)(this["cmbKey15"]));
            }
            set {
                this["cmbKey15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Move")]
        public string cmbKey16 {
            get {
                return ((string)(this["cmbKey16"]));
            }
            set {
                this["cmbKey16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Slide")]
        public string cmbKey17 {
            get {
                return ((string)(this["cmbKey17"]));
            }
            set {
                this["cmbKey17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Slip")]
        public string cmbKey18 {
            get {
                return ((string)(this["cmbKey18"]));
            }
            set {
                this["cmbKey18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Source/Timeline Viewer")]
        public string cmbKey19 {
            get {
                return ((string)(this["cmbKey19"]));
            }
            set {
                this["cmbKey19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Project Settings")]
        public string cmbKey20 {
            get {
                return ((string)(this["cmbKey20"]));
            }
            set {
                this["cmbKey20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Source Clip/Tape")]
        public string cmbKey21 {
            get {
                return ((string)(this["cmbKey21"]));
            }
            set {
                this["cmbKey21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shuttle")]
        public string cmbKey22 {
            get {
                return ((string)(this["cmbKey22"]));
            }
            set {
                this["cmbKey22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jog")]
        public string cmbKey23 {
            get {
                return ((string)(this["cmbKey23"]));
            }
            set {
                this["cmbKey23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Scroll")]
        public string cmbKey24 {
            get {
                return ((string)(this["cmbKey24"]));
            }
            set {
                this["cmbKey24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pause/Start Playback")]
        public string cmbKey25 {
            get {
                return ((string)(this["cmbKey25"]));
            }
            set {
                this["cmbKey25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Russian")]
        public string language {
            get {
                return ((string)(this["language"]));
            }
            set {
                this["language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor1 {
            get {
                return ((ushort)(this["cmbColor1"]));
            }
            set {
                this["cmbColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor2 {
            get {
                return ((ushort)(this["cmbColor2"]));
            }
            set {
                this["cmbColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor3 {
            get {
                return ((ushort)(this["cmbColor3"]));
            }
            set {
                this["cmbColor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor4 {
            get {
                return ((ushort)(this["cmbColor4"]));
            }
            set {
                this["cmbColor4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor5 {
            get {
                return ((ushort)(this["cmbColor5"]));
            }
            set {
                this["cmbColor5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor6 {
            get {
                return ((ushort)(this["cmbColor6"]));
            }
            set {
                this["cmbColor6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor7 {
            get {
                return ((ushort)(this["cmbColor7"]));
            }
            set {
                this["cmbColor7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor8 {
            get {
                return ((ushort)(this["cmbColor8"]));
            }
            set {
                this["cmbColor8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor9 {
            get {
                return ((ushort)(this["cmbColor9"]));
            }
            set {
                this["cmbColor9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor10 {
            get {
                return ((ushort)(this["cmbColor10"]));
            }
            set {
                this["cmbColor10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor11 {
            get {
                return ((ushort)(this["cmbColor11"]));
            }
            set {
                this["cmbColor11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor12 {
            get {
                return ((ushort)(this["cmbColor12"]));
            }
            set {
                this["cmbColor12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor13 {
            get {
                return ((ushort)(this["cmbColor13"]));
            }
            set {
                this["cmbColor13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor14 {
            get {
                return ((ushort)(this["cmbColor14"]));
            }
            set {
                this["cmbColor14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor15 {
            get {
                return ((ushort)(this["cmbColor15"]));
            }
            set {
                this["cmbColor15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor16 {
            get {
                return ((ushort)(this["cmbColor16"]));
            }
            set {
                this["cmbColor16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor17 {
            get {
                return ((ushort)(this["cmbColor17"]));
            }
            set {
                this["cmbColor17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor18 {
            get {
                return ((ushort)(this["cmbColor18"]));
            }
            set {
                this["cmbColor18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor19 {
            get {
                return ((ushort)(this["cmbColor19"]));
            }
            set {
                this["cmbColor19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor20 {
            get {
                return ((ushort)(this["cmbColor20"]));
            }
            set {
                this["cmbColor20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor21 {
            get {
                return ((ushort)(this["cmbColor21"]));
            }
            set {
                this["cmbColor21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor22 {
            get {
                return ((ushort)(this["cmbColor22"]));
            }
            set {
                this["cmbColor22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor23 {
            get {
                return ((ushort)(this["cmbColor23"]));
            }
            set {
                this["cmbColor23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor24 {
            get {
                return ((ushort)(this["cmbColor24"]));
            }
            set {
                this["cmbColor24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort cmbColor25 {
            get {
                return ((ushort)(this["cmbColor25"]));
            }
            set {
                this["cmbColor25"] = value;
            }
        }
    }
}
