#pragma once

/* Настройка USB информации о клавиатуре */
#define USB_MANUFACTURER "Sklyar Roman S-LAB"
#define USB_PRODUCT      "Mini Editor Keyboard"
#define USB_SERIAL       __DATE__ " v1.0"
/* Значение переключения действий в actionScroll() (миллисекунды) */
#define SCROLL_INTERVAL 50
/* Управление состоянием USB */
enum USBState {
  CONNECT,
  DISCONNECT,
  SETUP,
};
/** 
 * Значения EEPROM.
 * Клавиш всего 25 (0 - 24).
 */
#define KEYS_COUNT 25
enum EEPROMParameters {
  ADDR_TOOLS_START = 0,
  ADDR_TOOLS_END   = ADDR_TOOLS_START + KEYS_COUNT -1,
  ADDR_COLORS_START = ADDR_TOOLS_END + 1,
  ADDR_COLORS_END = ADDR_COLORS_START + KEYS_COUNT - 1,
  EEP_ADDR_CHECK = ADDR_COLORS_END + 1,
  EEP_PAGE_BEGIN  = 0x801F800,
  EEP_PAGE_SIZE  = 0x400, // 1K
  EEP_KEY_EMPTY   = 0x2021,
};
/* Управление ручкой поиска */
enum WheelParameters {
  NUDGE,
  SHUTTLE,
  JOG,
  SCROLL,
  AUDIO,
  SWAP,
  SUB_MODE_OFF,
  NEUTRAL = 0,
  MAXIMUM = 6,
  MINIMUM = -MAXIMUM,
  LEFT    = true,
  RIGHT   = false,
};
/* Режимы светодиодов */
enum LEDModes {
  LED_SHUTTLE,
  LED_JOG,
  LED_SCROLL,
  LEDs_OFF,
};
/**
 * Номер инструмента хранящийся в EEPROM.
 * Предельное значение 65535 (Эта EEPROM.h может).
 */
enum ToolsNumber {
  TOOL_NONE,                            // 0
  TOOL_UNDO,
  TOOL_SNAPPING,
  TOOL_CINEMA_VIEWER,
  TOOL_INSERT,
  TOOL_APPEND_TO_END_OF_TIMELINE,       // 5
  TOOL_RIPPLE_OVERWRITE,
  TOOL_FIT_TO_FILL,
  TOOL_PLACE_ON_TOP,
  TOOL_REPLACE,
  TOOL_MARK_IN,                         // 10
  TOOL_ADD_MARKER,
  TOOL_MARK_OUT,
  TOOL_RESIZE_IN,
  TOOL_RESIZE_OUT,
  TOOL_ROLL,                            // 15
  TOOL_MOVE,
  TOOL_SLIDE,
  TOOL_SLIP,
  TOOL_SOURCE_TIMELINE_VIEWER,
  TOOL_PROJECT_SETTINGS,                // 20
  TOOL_SOURCE_CLIP_TAPE,
  TOOL_WHEEL_SHUTTLE,
  TOOL_WHEEL_JOG,
  TOOL_WHEEL_SCROLL,
  TOOL_PAUSE_START_PLAYBACK,            // 25
  TOOL_PLAY_REVERS,
  TOOL_PLAY_FORWARD,
  TOOL_GO_TO_IN,
  TOOL_GO_TO_OUT,
  TOOL_RIPLE_START_TO_PLAYHEAD,         // 30
  TOOL_RIPLE_END_TO_PLAYHEAD,
  TOOL_PREVIOUS_CLIP_EDIT,
  TOOL_NEXT_CLIP_EDIT,
  TOOL_FAST_REVERSE,
  TOOL_FAST_FORWARD,                    // 35
  TOOL_FRAME_REVERSE,
  TOOL_FRAME_FORWARD,
  TOOL_ONE_FRAME_LEFT,
  TOOL_ONE_FRAME_RIGHT,
  TOOL_TIMELINE_START,                  // 40
  TOOL_TIMELINE_END,
  TOOL_MULTIFRAME_LEFT,
  TOOL_MULTIFRAME_RIGHT,
  TOOL_ONE_SECOND_REVERSE,
  TOOL_ONE_SECOND_FORWARD,              // 45
  TOOL_CHANGE_CLIP_SPEED,
  TOOL_CHANGE_CLIP_DURATION,
  TOOL_SHOW_CURVE_EDITOR,
  TOOL_SHOW_KEYFRAME_EDITOR,
  TOOL_SELECT_NEAREST_VIDEO_EDIT_PIONT, // 50
  TOOL_SELECT_NEAREST_AUDIO_EDIT_PIONT,
  TOOL_DECREASE_AUDIO_LEVEL_1DB,
  TOOL_INCREASE_AUDIO_LEVEL_1DB,
  TOOL_MARK_CLIP,
  TOOL_CLEAR_IN,                        // 55
  TOOL_CLEAR_OUT,
  TOOL_CLEAR_IN_AND_OUT,
  TOOL_ADD_TRANSITION,
  TOOL_ADD_VIDEO_ONLY_TRANSITION,
  TOOL_ADD_AUDIO_ONLY_TRANSITION,       // 60
  TOOL_SELECT_NEAREST_CLIP_GAP,
  TOOL_SELECT_NEAREST_EDIT_POINT,
  TOOL_PROJECT_MANAGER,
  TOOL_SWITCH_TO_PAGE_MEDIA,
  TOOL_SWITCH_TO_PAGE_CUT,              // 65
  TOOL_SWITCH_TO_PAGE_EDIT,
  TOOL_SWITCH_TO_PAGE_FUSION,
  TOOL_SWITCH_TO_PAGE_COLOR,
  TOOL_SWITCH_TO_PAGE_FAIRLIGHT,
  TOOL_SWITCH_TO_PAGE_DELIVER,          // 70
  TOOL_CUT_TO_ANGLE_1,
  TOOL_CUT_TO_ANGLE_2,
  TOOL_CUT_TO_ANGLE_3,
  TOOL_CUT_TO_ANGLE_4,
  TOOL_CUT_TO_ANGLE_5,                  // 75
  TOOL_CUT_TO_ANGLE_6,
  TOOL_CUT_TO_ANGLE_7,
  TOOL_CUT_TO_ANGLE_8,
  TOOL_CUT_TO_ANGLE_9,
  TOOL_SAVE_PROJECT,                    // 80
  TOOL_SAVE_PROJECT_AS,
  TOOL_SWAP_CLIPS_TOWARDS_LEFT,
  TOOL_SWAP_CLIPS_TOWARDS_RIGHT,
  TOOL_SELECT_ALL,
  TOOL_DESELECT_ALL,                    // 85
  TOOL_REDO,
  TOOL_DELETE_MARKER,
  TOOL_RIPPLE_DELETE,
  TOOL_OVERWRITE,
  TOOL_SPLIT_CLIP,                      // 90
  TOOL_DELETE_GAPS,
  TOOL_STOP,
  TOOL_PLAY_SLOW,
  TOOL_COPY,
  TOOL_CUT,                             // 95
  TOOL_PASTE,
  TOOL_ENABLE_CLIP,
  TOOL_PREFERENCES,
  TOOL_LOOP_UNLOOP,
  TOOL_FREEZE_FRAME,                    // 100
  TOOL_CHANGE_AUDIO_LEVEL,
  TOOL_SWAP_CLIPS,
  TOOL_LINKED_SELECTION,
  TOOL_KEYBOARD_CUSTOMIZATION,
  TOOL_QUIT_DAVINCI_RESOLVE,            // 105
  TOOL_NEW_TIMELINE,
  TOOL_INPORT_MEDIA,
  TOOL_SYNC_BIN,
};
/**
 * Цвето колпачков клавиш хранящийся в EEPROM.
 * Предельное значение 65535 (EEPROM.h может).
 */
enum ColorsNumber {
  COLOR_BLACK, // 0
  COLOR_WHITE,
  COLOR_SILVER,
  COLOR_RED,
  COLOR_GREEN,
  COLOR_BLUE, // 5
  COLOR_7,
  COLOR_8,
  COLOR_9,
  COLOR_10,
  COLOR_11, // 10
  COLOR_12,
  COLOR_13,
  COLOR_14,
  COLOR_15,
  COLOR_16, // 15
  COLOR_17,
  COLOR_18,
  COLOR_19,
  COLOR_20,
  COLOR_21, // 20
  COLOR_22,
  COLOR_23,
  COLOR_24,
  COLOR_25,
};
