//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programmer.Languages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Programmer.Languages.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Binary file (*.bin)|*.bin.
        /// </summary>
        internal static string fd_binary_filter {
            get {
                return ResourceManager.GetString("fd_binary_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Layout file (*.mek)|*.mek.
        /// </summary>
        internal static string fd_layout_filter {
            get {
                return ResourceManager.GetString("fd_layout_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mini Editor Keyboard Configurator.
        /// </summary>
        internal static string form_main_text {
            get {
                return ResourceManager.GetString("form_main_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на key_colors_en.
        /// </summary>
        internal static string key_colors_list_name {
            get {
                return ResourceManager.GetString("key_colors_list_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color:.
        /// </summary>
        internal static string lable_color_text {
            get {
                return ResourceManager.GetString("lable_color_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description:.
        /// </summary>
        internal static string lable_description_text {
            get {
                return ResourceManager.GetString("lable_description_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 1.
        /// </summary>
        internal static string lable_key_1 {
            get {
                return ResourceManager.GetString("lable_key_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 10.
        /// </summary>
        internal static string lable_key_10 {
            get {
                return ResourceManager.GetString("lable_key_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 11.
        /// </summary>
        internal static string lable_key_11 {
            get {
                return ResourceManager.GetString("lable_key_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 12.
        /// </summary>
        internal static string lable_key_12 {
            get {
                return ResourceManager.GetString("lable_key_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 13.
        /// </summary>
        internal static string lable_key_13 {
            get {
                return ResourceManager.GetString("lable_key_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 14.
        /// </summary>
        internal static string lable_key_14 {
            get {
                return ResourceManager.GetString("lable_key_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 15.
        /// </summary>
        internal static string lable_key_15 {
            get {
                return ResourceManager.GetString("lable_key_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 16.
        /// </summary>
        internal static string lable_key_16 {
            get {
                return ResourceManager.GetString("lable_key_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 17.
        /// </summary>
        internal static string lable_key_17 {
            get {
                return ResourceManager.GetString("lable_key_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 18.
        /// </summary>
        internal static string lable_key_18 {
            get {
                return ResourceManager.GetString("lable_key_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 19.
        /// </summary>
        internal static string lable_key_19 {
            get {
                return ResourceManager.GetString("lable_key_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 2.
        /// </summary>
        internal static string lable_key_2 {
            get {
                return ResourceManager.GetString("lable_key_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 20.
        /// </summary>
        internal static string lable_key_20 {
            get {
                return ResourceManager.GetString("lable_key_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 21.
        /// </summary>
        internal static string lable_key_21 {
            get {
                return ResourceManager.GetString("lable_key_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 22.
        /// </summary>
        internal static string lable_key_22 {
            get {
                return ResourceManager.GetString("lable_key_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 23.
        /// </summary>
        internal static string lable_key_23 {
            get {
                return ResourceManager.GetString("lable_key_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 24.
        /// </summary>
        internal static string lable_key_24 {
            get {
                return ResourceManager.GetString("lable_key_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 25.
        /// </summary>
        internal static string lable_key_25 {
            get {
                return ResourceManager.GetString("lable_key_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 3.
        /// </summary>
        internal static string lable_key_3 {
            get {
                return ResourceManager.GetString("lable_key_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 4.
        /// </summary>
        internal static string lable_key_4 {
            get {
                return ResourceManager.GetString("lable_key_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 5.
        /// </summary>
        internal static string lable_key_5 {
            get {
                return ResourceManager.GetString("lable_key_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 6.
        /// </summary>
        internal static string lable_key_6 {
            get {
                return ResourceManager.GetString("lable_key_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 7.
        /// </summary>
        internal static string lable_key_7 {
            get {
                return ResourceManager.GetString("lable_key_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 8.
        /// </summary>
        internal static string lable_key_8 {
            get {
                return ResourceManager.GetString("lable_key_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key 9.
        /// </summary>
        internal static string lable_key_9 {
            get {
                return ResourceManager.GetString("lable_key_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shortcut:.
        /// </summary>
        internal static string lable_keys_text {
            get {
                return ResourceManager.GetString("lable_keys_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note:.
        /// </summary>
        internal static string lable_note_text {
            get {
                return ResourceManager.GetString("lable_note_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check.
        /// </summary>
        internal static string menu_check {
            get {
                return ResourceManager.GetString("menu_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Communication DFU.
        /// </summary>
        internal static string menu_check_dfu {
            get {
                return ResourceManager.GetString("menu_check_dfu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Communication SWD.
        /// </summary>
        internal static string menu_check_swd {
            get {
                return ResourceManager.GetString("menu_check_swd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Driver.
        /// </summary>
        internal static string menu_driver {
            get {
                return ResourceManager.GetString("menu_driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Install DFU.
        /// </summary>
        internal static string menu_driver_dfu {
            get {
                return ResourceManager.GetString("menu_driver_dfu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Install SWD.
        /// </summary>
        internal static string menu_driver_st_link {
            get {
                return ResourceManager.GetString("menu_driver_st_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export.
        /// </summary>
        internal static string menu_export {
            get {
                return ResourceManager.GetString("menu_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All flash.
        /// </summary>
        internal static string menu_export_all_flash {
            get {
                return ResourceManager.GetString("menu_export_all_flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bootloader.
        /// </summary>
        internal static string menu_export_bootloader {
            get {
                return ResourceManager.GetString("menu_export_bootloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Firmware.
        /// </summary>
        internal static string menu_export_firmware {
            get {
                return ResourceManager.GetString("menu_export_firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tools.
        /// </summary>
        internal static string menu_export_tools {
            get {
                return ResourceManager.GetString("menu_export_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import.
        /// </summary>
        internal static string menu_import {
            get {
                return ResourceManager.GetString("menu_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All flash.
        /// </summary>
        internal static string menu_import_all_flash {
            get {
                return ResourceManager.GetString("menu_import_all_flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bootloader.
        /// </summary>
        internal static string menu_import_bootloader {
            get {
                return ResourceManager.GetString("menu_import_bootloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Firmware.
        /// </summary>
        internal static string menu_import_firmware {
            get {
                return ResourceManager.GetString("menu_import_firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tools.
        /// </summary>
        internal static string menu_import_tools {
            get {
                return ResourceManager.GetString("menu_import_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        internal static string menu_language {
            get {
                return ResourceManager.GetString("menu_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Layout.
        /// </summary>
        internal static string menu_layout {
            get {
                return ResourceManager.GetString("menu_layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        internal static string menu_layout_open {
            get {
                return ResourceManager.GetString("menu_layout_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restore.
        /// </summary>
        internal static string menu_layout_restore {
            get {
                return ResourceManager.GetString("menu_layout_restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string menu_layout_save {
            get {
                return ResourceManager.GetString("menu_layout_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read.
        /// </summary>
        internal static string menu_read {
            get {
                return ResourceManager.GetString("menu_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All flash (SWD).
        /// </summary>
        internal static string menu_read_all_flash {
            get {
                return ResourceManager.GetString("menu_read_all_flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bootloader (SWD).
        /// </summary>
        internal static string menu_read_bootloader {
            get {
                return ResourceManager.GetString("menu_read_bootloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Firmware (DFU).
        /// </summary>
        internal static string menu_read_firmware {
            get {
                return ResourceManager.GetString("menu_read_firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tools (DFU).
        /// </summary>
        internal static string menu_read_tools {
            get {
                return ResourceManager.GetString("menu_read_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write.
        /// </summary>
        internal static string menu_write {
            get {
                return ResourceManager.GetString("menu_write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All flash (SWD).
        /// </summary>
        internal static string menu_write_all_flash {
            get {
                return ResourceManager.GetString("menu_write_all_flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bootloader (SWD).
        /// </summary>
        internal static string menu_write_bootloader {
            get {
                return ResourceManager.GetString("menu_write_bootloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Firmware (DFU).
        /// </summary>
        internal static string menu_write_firmware {
            get {
                return ResourceManager.GetString("menu_write_firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tools (DFU).
        /// </summary>
        internal static string menu_write_tools {
            get {
                return ResourceManager.GetString("menu_write_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string message_caption_error {
            get {
                return ResourceManager.GetString("message_caption_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notice.
        /// </summary>
        internal static string message_caption_information {
            get {
                return ResourceManager.GetString("message_caption_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        internal static string message_caption_warning {
            get {
                return ResourceManager.GetString("message_caption_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language changed. The program will restart.
        /// </summary>
        internal static string message_change_language {
            get {
                return ResourceManager.GetString("message_change_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to install keyboard driver.
        /// </summary>
        internal static string message_dfu_error {
            get {
                return ResourceManager.GetString("message_dfu_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keyboard driver installed successfully.
        /// </summary>
        internal static string message_dfu_success {
            get {
                return ResourceManager.GetString("message_dfu_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The keyboard is detected in DFU mode!.
        /// </summary>
        internal static string message_dfuutil_device_found {
            get {
                return ResourceManager.GetString("message_dfuutil_device_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No keyboard detected in DFU mode!.
        /// </summary>
        internal static string message_dfuutil_device_not_found {
            get {
                return ResourceManager.GetString("message_dfuutil_device_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Firmware reading completed!.
        /// </summary>
        internal static string message_dfuutil_read_firmware_done {
            get {
                return ResourceManager.GetString("message_dfuutil_read_firmware_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tools reading completed!.
        /// </summary>
        internal static string message_dfuutil_read_tools_done {
            get {
                return ResourceManager.GetString("message_dfuutil_read_tools_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Firmware writing completed!.
        /// </summary>
        internal static string message_dfuutil_write_firmware_done {
            get {
                return ResourceManager.GetString("message_dfuutil_write_firmware_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tools writing completed!.
        /// </summary>
        internal static string message_dfuutil_write_tools_done {
            get {
                return ResourceManager.GetString("message_dfuutil_write_tools_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All flash file exported successfully!.
        /// </summary>
        internal static string message_export_all_flash_success {
            get {
                return ResourceManager.GetString("message_export_all_flash_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bootloader file exported successfully!.
        /// </summary>
        internal static string message_export_bootloader_success {
            get {
                return ResourceManager.GetString("message_export_bootloader_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export failed!.
        /// </summary>
        internal static string message_export_error {
            get {
                return ResourceManager.GetString("message_export_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Firmware file exported successfully!.
        /// </summary>
        internal static string message_export_firmware_success {
            get {
                return ResourceManager.GetString("message_export_firmware_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tools file exported successfully!.
        /// </summary>
        internal static string message_export_tools_success {
            get {
                return ResourceManager.GetString("message_export_tools_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All flash file imported successfully!.
        /// </summary>
        internal static string message_import_all_flash_success {
            get {
                return ResourceManager.GetString("message_import_all_flash_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bootloader file imported successfully!.
        /// </summary>
        internal static string message_import_bootloader_success {
            get {
                return ResourceManager.GetString("message_import_bootloader_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import failed!.
        /// </summary>
        internal static string message_import_error {
            get {
                return ResourceManager.GetString("message_import_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Firmware file imported successfully!.
        /// </summary>
        internal static string message_import_firmware_success {
            get {
                return ResourceManager.GetString("message_import_firmware_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tools file imported successfully!.
        /// </summary>
        internal static string message_import_tools_success {
            get {
                return ResourceManager.GetString("message_import_tools_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to open the layout file!.
        /// </summary>
        internal static string message_layout_error {
            get {
                return ResourceManager.GetString("message_layout_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The keyboard is detected SWD mode!.
        /// </summary>
        internal static string message_stlink_device_found {
            get {
                return ResourceManager.GetString("message_stlink_device_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No keyboard detected in SWD mode!.
        /// </summary>
        internal static string message_stlink_device_not_found {
            get {
                return ResourceManager.GetString("message_stlink_device_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All flash has been read successfully!.
        /// </summary>
        internal static string message_stlink_dump_all_flash_success {
            get {
                return ResourceManager.GetString("message_stlink_dump_all_flash_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bootloader read successfully!.
        /// </summary>
        internal static string message_stlink_dump_bootloader_success {
            get {
                return ResourceManager.GetString("message_stlink_dump_bootloader_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown ST-Link error.
        /// </summary>
        internal static string message_stlink_error {
            get {
                return ResourceManager.GetString("message_stlink_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ST-Link programmer not found!.
        /// </summary>
        internal static string message_stlink_st_link_not_found {
            get {
                return ResourceManager.GetString("message_stlink_st_link_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All flash has been successfully written!.
        /// </summary>
        internal static string message_stlink_write_all_flash_done {
            get {
                return ResourceManager.GetString("message_stlink_write_all_flash_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bootloader was written successfully!.
        /// </summary>
        internal static string message_stlink_write_bootloader_done {
            get {
                return ResourceManager.GetString("message_stlink_write_bootloader_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to install ST-Link programmer driver.
        /// </summary>
        internal static string message_swd_error {
            get {
                return ResourceManager.GetString("message_swd_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ST-Link programmer driver successfully installed.
        /// </summary>
        internal static string message_swd_success {
            get {
                return ResourceManager.GetString("message_swd_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import file.
        /// </summary>
        internal static string ofd_import {
            get {
                return ResourceManager.GetString("ofd_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open file.
        /// </summary>
        internal static string ofd_open {
            get {
                return ResourceManager.GetString("ofd_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save file.
        /// </summary>
        internal static string ofd_save {
            get {
                return ResourceManager.GetString("ofd_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export file.
        /// </summary>
        internal static string sfd_export {
            get {
                return ResourceManager.GetString("sfd_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на key_tools_en.
        /// </summary>
        internal static string tools_list_name {
            get {
                return ResourceManager.GetString("tools_list_name", resourceCulture);
            }
        }
    }
}
