//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programmer.Languages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Russian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Russian() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Programmer.Languages.Russian", typeof(Russian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бинарный файл (*.bin)|*.bin.
        /// </summary>
        internal static string fd_binary_filter {
            get {
                return ResourceManager.GetString("fd_binary_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл раскладки (*.mek)|*.mek.
        /// </summary>
        internal static string fd_layout_filter {
            get {
                return ResourceManager.GetString("fd_layout_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конфигуратор Mini Editor Keyboard.
        /// </summary>
        internal static string form_main_text {
            get {
                return ResourceManager.GetString("form_main_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на key_colors_ru.
        /// </summary>
        internal static string key_colors_list_name {
            get {
                return ResourceManager.GetString("key_colors_list_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет:.
        /// </summary>
        internal static string lable_color_text {
            get {
                return ResourceManager.GetString("lable_color_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание:.
        /// </summary>
        internal static string lable_description_text {
            get {
                return ResourceManager.GetString("lable_description_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 1.
        /// </summary>
        internal static string lable_key_1 {
            get {
                return ResourceManager.GetString("lable_key_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 10.
        /// </summary>
        internal static string lable_key_10 {
            get {
                return ResourceManager.GetString("lable_key_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 11.
        /// </summary>
        internal static string lable_key_11 {
            get {
                return ResourceManager.GetString("lable_key_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 12.
        /// </summary>
        internal static string lable_key_12 {
            get {
                return ResourceManager.GetString("lable_key_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 13.
        /// </summary>
        internal static string lable_key_13 {
            get {
                return ResourceManager.GetString("lable_key_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 14.
        /// </summary>
        internal static string lable_key_14 {
            get {
                return ResourceManager.GetString("lable_key_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 15.
        /// </summary>
        internal static string lable_key_15 {
            get {
                return ResourceManager.GetString("lable_key_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 16.
        /// </summary>
        internal static string lable_key_16 {
            get {
                return ResourceManager.GetString("lable_key_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 17.
        /// </summary>
        internal static string lable_key_17 {
            get {
                return ResourceManager.GetString("lable_key_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 18.
        /// </summary>
        internal static string lable_key_18 {
            get {
                return ResourceManager.GetString("lable_key_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 19.
        /// </summary>
        internal static string lable_key_19 {
            get {
                return ResourceManager.GetString("lable_key_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 2.
        /// </summary>
        internal static string lable_key_2 {
            get {
                return ResourceManager.GetString("lable_key_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 20.
        /// </summary>
        internal static string lable_key_20 {
            get {
                return ResourceManager.GetString("lable_key_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 21.
        /// </summary>
        internal static string lable_key_21 {
            get {
                return ResourceManager.GetString("lable_key_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 22.
        /// </summary>
        internal static string lable_key_22 {
            get {
                return ResourceManager.GetString("lable_key_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 23.
        /// </summary>
        internal static string lable_key_23 {
            get {
                return ResourceManager.GetString("lable_key_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 24.
        /// </summary>
        internal static string lable_key_24 {
            get {
                return ResourceManager.GetString("lable_key_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 25.
        /// </summary>
        internal static string lable_key_25 {
            get {
                return ResourceManager.GetString("lable_key_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 3.
        /// </summary>
        internal static string lable_key_3 {
            get {
                return ResourceManager.GetString("lable_key_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 4.
        /// </summary>
        internal static string lable_key_4 {
            get {
                return ResourceManager.GetString("lable_key_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 5.
        /// </summary>
        internal static string lable_key_5 {
            get {
                return ResourceManager.GetString("lable_key_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 6.
        /// </summary>
        internal static string lable_key_6 {
            get {
                return ResourceManager.GetString("lable_key_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 7.
        /// </summary>
        internal static string lable_key_7 {
            get {
                return ResourceManager.GetString("lable_key_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 8.
        /// </summary>
        internal static string lable_key_8 {
            get {
                return ResourceManager.GetString("lable_key_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша 9.
        /// </summary>
        internal static string lable_key_9 {
            get {
                return ResourceManager.GetString("lable_key_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комбинация:.
        /// </summary>
        internal static string lable_keys_text {
            get {
                return ResourceManager.GetString("lable_keys_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примечание:.
        /// </summary>
        internal static string lable_note_text {
            get {
                return ResourceManager.GetString("lable_note_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверить.
        /// </summary>
        internal static string menu_check {
            get {
                return ResourceManager.GetString("menu_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь DFU.
        /// </summary>
        internal static string menu_check_dfu {
            get {
                return ResourceManager.GetString("menu_check_dfu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь SWD.
        /// </summary>
        internal static string menu_check_swd {
            get {
                return ResourceManager.GetString("menu_check_swd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Драйвер.
        /// </summary>
        internal static string menu_driver {
            get {
                return ResourceManager.GetString("menu_driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установить DFU.
        /// </summary>
        internal static string menu_driver_dfu {
            get {
                return ResourceManager.GetString("menu_driver_dfu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установить SWD.
        /// </summary>
        internal static string menu_driver_st_link {
            get {
                return ResourceManager.GetString("menu_driver_st_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспортировать.
        /// </summary>
        internal static string menu_export {
            get {
                return ResourceManager.GetString("menu_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всю память.
        /// </summary>
        internal static string menu_export_all_flash {
            get {
                return ResourceManager.GetString("menu_export_all_flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузчик.
        /// </summary>
        internal static string menu_export_bootloader {
            get {
                return ResourceManager.GetString("menu_export_bootloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прошивку.
        /// </summary>
        internal static string menu_export_firmware {
            get {
                return ResourceManager.GetString("menu_export_firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструменты.
        /// </summary>
        internal static string menu_export_tools {
            get {
                return ResourceManager.GetString("menu_export_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импортировать.
        /// </summary>
        internal static string menu_import {
            get {
                return ResourceManager.GetString("menu_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всю память.
        /// </summary>
        internal static string menu_import_all_flash {
            get {
                return ResourceManager.GetString("menu_import_all_flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузчик.
        /// </summary>
        internal static string menu_import_bootloader {
            get {
                return ResourceManager.GetString("menu_import_bootloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прошивку.
        /// </summary>
        internal static string menu_import_firmware {
            get {
                return ResourceManager.GetString("menu_import_firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструменты.
        /// </summary>
        internal static string menu_import_tools {
            get {
                return ResourceManager.GetString("menu_import_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        internal static string menu_language {
            get {
                return ResourceManager.GetString("menu_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Раскладка.
        /// </summary>
        internal static string menu_layout {
            get {
                return ResourceManager.GetString("menu_layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть.
        /// </summary>
        internal static string menu_layout_open {
            get {
                return ResourceManager.GetString("menu_layout_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановить.
        /// </summary>
        internal static string menu_layout_restore {
            get {
                return ResourceManager.GetString("menu_layout_restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string menu_layout_save {
            get {
                return ResourceManager.GetString("menu_layout_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Считать.
        /// </summary>
        internal static string menu_read {
            get {
                return ResourceManager.GetString("menu_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всю память (SWD).
        /// </summary>
        internal static string menu_read_all_flash {
            get {
                return ResourceManager.GetString("menu_read_all_flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузчик (SWD).
        /// </summary>
        internal static string menu_read_bootloader {
            get {
                return ResourceManager.GetString("menu_read_bootloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прошивку (DFU).
        /// </summary>
        internal static string menu_read_firmware {
            get {
                return ResourceManager.GetString("menu_read_firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструменты (DFU).
        /// </summary>
        internal static string menu_read_tools {
            get {
                return ResourceManager.GetString("menu_read_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Записать.
        /// </summary>
        internal static string menu_write {
            get {
                return ResourceManager.GetString("menu_write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всю память (SWD).
        /// </summary>
        internal static string menu_write_all_flash {
            get {
                return ResourceManager.GetString("menu_write_all_flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузчик (SWD).
        /// </summary>
        internal static string menu_write_bootloader {
            get {
                return ResourceManager.GetString("menu_write_bootloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прошивку (DFU).
        /// </summary>
        internal static string menu_write_firmware {
            get {
                return ResourceManager.GetString("menu_write_firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструменты (DFU).
        /// </summary>
        internal static string menu_write_tools {
            get {
                return ResourceManager.GetString("menu_write_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string message_caption_error {
            get {
                return ResourceManager.GetString("message_caption_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уведомление.
        /// </summary>
        internal static string message_caption_information {
            get {
                return ResourceManager.GetString("message_caption_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        internal static string message_caption_warning {
            get {
                return ResourceManager.GetString("message_caption_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык изменен. Программа перезагрузится.
        /// </summary>
        internal static string message_change_language {
            get {
                return ResourceManager.GetString("message_change_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось установить драйвер клавиатуры.
        /// </summary>
        internal static string message_dfu_error {
            get {
                return ResourceManager.GetString("message_dfu_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Драйвер клавиатуры успешно установлен.
        /// </summary>
        internal static string message_dfu_success {
            get {
                return ResourceManager.GetString("message_dfu_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиатура в режиме DFU обнаружена!.
        /// </summary>
        internal static string message_dfuutil_device_found {
            get {
                return ResourceManager.GetString("message_dfuutil_device_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиатура в режиме DFU не обнаружена!.
        /// </summary>
        internal static string message_dfuutil_device_not_found {
            get {
                return ResourceManager.GetString("message_dfuutil_device_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Считывание прошивки успешно завершено!.
        /// </summary>
        internal static string message_dfuutil_read_firmware_done {
            get {
                return ResourceManager.GetString("message_dfuutil_read_firmware_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Считывание инструментов успешно завершено!.
        /// </summary>
        internal static string message_dfuutil_read_tools_done {
            get {
                return ResourceManager.GetString("message_dfuutil_read_tools_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись прошивки успешно завершена!.
        /// </summary>
        internal static string message_dfuutil_write_firmware_done {
            get {
                return ResourceManager.GetString("message_dfuutil_write_firmware_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись инструментов успешно завершена!.
        /// </summary>
        internal static string message_dfuutil_write_tools_done {
            get {
                return ResourceManager.GetString("message_dfuutil_write_tools_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл всей памяти успешно экспортирован!.
        /// </summary>
        internal static string message_export_all_flash_success {
            get {
                return ResourceManager.GetString("message_export_all_flash_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл загрузчика успешно экспортирован!.
        /// </summary>
        internal static string message_export_bootloader_success {
            get {
                return ResourceManager.GetString("message_export_bootloader_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось выполнить экспорт!.
        /// </summary>
        internal static string message_export_error {
            get {
                return ResourceManager.GetString("message_export_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл прошивки успешно экспортирован!.
        /// </summary>
        internal static string message_export_firmware_success {
            get {
                return ResourceManager.GetString("message_export_firmware_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл инструментов успешно экспортирован!.
        /// </summary>
        internal static string message_export_tools_success {
            get {
                return ResourceManager.GetString("message_export_tools_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл всей памяти успешно импортирован!.
        /// </summary>
        internal static string message_import_all_flash_success {
            get {
                return ResourceManager.GetString("message_import_all_flash_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл загрузчика успешно импортирован!.
        /// </summary>
        internal static string message_import_bootloader_success {
            get {
                return ResourceManager.GetString("message_import_bootloader_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось выполнить импорт!.
        /// </summary>
        internal static string message_import_error {
            get {
                return ResourceManager.GetString("message_import_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл прошивки успешно импортирован!.
        /// </summary>
        internal static string message_import_firmware_success {
            get {
                return ResourceManager.GetString("message_import_firmware_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл инструментов успешно импортирован!.
        /// </summary>
        internal static string message_import_tools_success {
            get {
                return ResourceManager.GetString("message_import_tools_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось открыть файл раскладки!.
        /// </summary>
        internal static string message_layout_error {
            get {
                return ResourceManager.GetString("message_layout_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиатура в режиме SWD обнаружена!.
        /// </summary>
        internal static string message_stlink_device_found {
            get {
                return ResourceManager.GetString("message_stlink_device_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиатура в режиме SWD не обнаружена!.
        /// </summary>
        internal static string message_stlink_device_not_found {
            get {
                return ResourceManager.GetString("message_stlink_device_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вся память успешно считана!.
        /// </summary>
        internal static string message_stlink_dump_all_flash_success {
            get {
                return ResourceManager.GetString("message_stlink_dump_all_flash_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузчик успешно считан!.
        /// </summary>
        internal static string message_stlink_dump_bootloader_success {
            get {
                return ResourceManager.GetString("message_stlink_dump_bootloader_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестная ошибка ST-Link.
        /// </summary>
        internal static string message_stlink_error {
            get {
                return ResourceManager.GetString("message_stlink_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Программатор ST-Link не обнаружен!.
        /// </summary>
        internal static string message_stlink_st_link_not_found {
            get {
                return ResourceManager.GetString("message_stlink_st_link_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вся память успешно записана!.
        /// </summary>
        internal static string message_stlink_write_all_flash_done {
            get {
                return ResourceManager.GetString("message_stlink_write_all_flash_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузчик успешно записан!.
        /// </summary>
        internal static string message_stlink_write_bootloader_done {
            get {
                return ResourceManager.GetString("message_stlink_write_bootloader_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось установить драйвер программатора ST-Link.
        /// </summary>
        internal static string message_swd_error {
            get {
                return ResourceManager.GetString("message_swd_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Драйвер программатора ST-Link успешно установлен.
        /// </summary>
        internal static string message_swd_success {
            get {
                return ResourceManager.GetString("message_swd_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импортировать файл.
        /// </summary>
        internal static string ofd_import {
            get {
                return ResourceManager.GetString("ofd_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть файл.
        /// </summary>
        internal static string ofd_open {
            get {
                return ResourceManager.GetString("ofd_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить файл.
        /// </summary>
        internal static string ofd_save {
            get {
                return ResourceManager.GetString("ofd_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспортировать файл.
        /// </summary>
        internal static string sfd_export {
            get {
                return ResourceManager.GetString("sfd_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на key_tools_ru.
        /// </summary>
        internal static string tools_list_name {
            get {
                return ResourceManager.GetString("tools_list_name", resourceCulture);
            }
        }
    }
}
